name:                 hedgehog-arrow
version:              0.1.0.0
visibility:           public
id:                   hedgehog-arrow-0.1.0.0-inplace
key:                  hedgehog-arrow-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            © 2026 anonymous
maintainer:           anonymous@gmail.com
author:               anonymous
synopsis:
    An arrow-based interface for implementing Hedgehog generators

category:             Testing
abi:                  inplace
exposed:              True
exposed-modules:
    Hedgehog.Arrow Hedgehog.Arrow.Gen Hedgehog.Arrow.Prelude

import-dirs:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/build

library-dirs:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/build

library-dirs-static:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/build

dynamic-library-dirs:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/build

data-dir:             /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/.
hs-libraries:         HShedgehog-arrow-0.1.0.0-inplace
depends:
    arrows-0.4.4.2-ca00fc3491387362acb469eda43d7714b2b4848792c4dcb23baa72bd697195cf
    base-4.20.2.0-2c2a bytestring-0.12.2.0-e560
    containers-0.6.8-537a46fd2565c52bf801f68aab542856ffefc00f1a90c4f6957a71570e96e1d5
    deepseq-1.5.0.0-7bf3
    hedgehog-1.7-819685ba0b52fcc9fff4de95556d1e32d59ed7b175fb1d0230d2e902027e80bf
    mtl-2.3.1-83b5
    text-2.1.4-c447954d960019a7c6fed8727a9519f00647e9f62f9e145f36faee9b09e34178
    transformers-0.6.1.1-eeae

haddock-interfaces:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/doc/html/hedgehog-arrow/hedgehog-arrow.haddock

haddock-html:
    /home/vandikas/Documents/hedgehog-arr/hedgehog-arr/dist-newstyle/build/x86_64-linux/ghc-9.10.3/hedgehog-arrow-0.1.0.0/doc/html/hedgehog-arrow
